name: Update Playlist

permissions:
  contents: write

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download playlist
        run: |
          curl -L \
          -H "User-Agent: OTT Navigator/1.6.9.4 (Linux;Android 10)" \
          -H "Referer: https://la.drmlive.net/" \
          -H "Origin: https://la.drmlive.net" \
          "https://la.drmlive.net/tp/playlist" \
          -o playlist.m3u

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add playlist.m3u
          git commit -m "Auto update playlist" || echo "No changes"
          git pull --rebase origin main
          git push origin main
